name: myweb.ci

trigger:
- master

pool:
  vmImage: ubuntu-latest
batch: true

pool:
  vmImage: 'ubantu-latest'
  variables:
  buildconfigurations: 'Release'
  steps:

Settings
- task: UseDotNet@2
  displayName: 'Install .NET core sdk'
  inputs:
   version: 3.1.x
   performMultiLeavelLookup: true

   Settings
- task: UseDotNet@2
  inputs:
  version: '3.1.x'
  displayName: set dotnet version to use

Settings
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    testRunTitle: 'TestRun_$(build.buildnumber)'

- task: DotNetCoreCLI@2
  displayName: binaries
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactsStagingDirectory)'

Settings
- task: PublishBuildArtifacts@1
  displayName: publish
  inputs:
   PathtoPublish: 'output $(Build.ArtifactsStagingDirectory)'
   ArtifactName: 'myweb'